version: '3.3'

services:
    dto2data_php:
        image: dh.rinsvent.ru/php8dev
        container_name: dto2data_php
        volumes:
            - ./:/app
        environment:
            USE_COMPOSER_SCRIPTS: 1
            PHP_IDE_CONFIG: "serverName=dto2data_php"

networks:
    default:
        external:
            name: full-project
